name: Build and Deploy
on:
  pull_request:

jobs:
  experiment:
    name: My Experiment
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Hello World"
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run docker action
        uses: nils-borrmann-y42/gh-action@master


