name: Build and Deploy
on:
  pull_request:

jobs:
  experiment:
    name: My Experiment
    runs-on: ubuntu-latest
    steps:
      - name: Diff poetry.lock
        uses: nborrmann/diff-poetry-lock@v1.0.0
